/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as LyricsRouteImport } from './routes/lyrics'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ApiFilmsIdRouteImport } from './routes/api/films.$id'
import { Route as ApiStationsSlugAudioRouteImport } from './routes/api/stations.$slug.audio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsRoute = LyricsRouteImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilmsIdRoute = ApiFilmsIdRouteImport.update({
  id: '/api/films/$id',
  path: '/api/films/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStationsSlugAudioRoute = ApiStationsSlugAudioRouteImport.update({
  id: '/api/stations/$slug/audio',
  path: '/api/stations/$slug/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/enter': typeof EnterRoute
  '/lyrics': typeof LyricsRoute
  '/support': typeof SupportRoute
  '/api/films/$id': typeof ApiFilmsIdRoute
  '/api/stations/$slug/audio': typeof ApiStationsSlugAudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/enter': typeof EnterRoute
  '/lyrics': typeof LyricsRoute
  '/support': typeof SupportRoute
  '/api/films/$id': typeof ApiFilmsIdRoute
  '/api/stations/$slug/audio': typeof ApiStationsSlugAudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/enter': typeof EnterRoute
  '/lyrics': typeof LyricsRoute
  '/support': typeof SupportRoute
  '/api/films/$id': typeof ApiFilmsIdRoute
  '/api/stations/$slug/audio': typeof ApiStationsSlugAudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/enter'
    | '/lyrics'
    | '/support'
    | '/api/films/$id'
    | '/api/stations/$slug/audio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/enter'
    | '/lyrics'
    | '/support'
    | '/api/films/$id'
    | '/api/stations/$slug/audio'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/enter'
    | '/lyrics'
    | '/support'
    | '/api/films/$id'
    | '/api/stations/$slug/audio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  EnterRoute: typeof EnterRoute
  LyricsRoute: typeof LyricsRoute
  SupportRoute: typeof SupportRoute
  ApiFilmsIdRoute: typeof ApiFilmsIdRoute
  ApiStationsSlugAudioRoute: typeof ApiStationsSlugAudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/films/$id': {
      id: '/api/films/$id'
      path: '/api/films/$id'
      fullPath: '/api/films/$id'
      preLoaderRoute: typeof ApiFilmsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stations/$slug/audio': {
      id: '/api/stations/$slug/audio'
      path: '/api/stations/$slug/audio'
      fullPath: '/api/stations/$slug/audio'
      preLoaderRoute: typeof ApiStationsSlugAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  EnterRoute: EnterRoute,
  LyricsRoute: LyricsRoute,
  SupportRoute: SupportRoute,
  ApiFilmsIdRoute: ApiFilmsIdRoute,
  ApiStationsSlugAudioRoute: ApiStationsSlugAudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
